### ISSUE TITLE
Unable to check stock of an item, response includes code 606.

### ISSUE THREAD

**Issue by RCRalph** [vrslev/ikea-api-client#110]
Hi, I've been trying to use your API to check stock of an item, to do this I used the following code:
```py
import ikea_api

constants = ikea_api.Constants(country="pl", language="pl")
stock = ikea_api.Stock(constants)
endpoint = stock.get_stock("00366301")

print(ikea_api.run(endpoint))
```

This prints out the following message:
```js
{'code': 606, 'message': 'classUnitType in path should be one of [ru sto]'}
```

And I'm stuck right here, I have no idea what can I do to fix this issue.  
Is there anything I can do to fix this? Thanks for reading : )

RCRalph

**Comment by vrslev** [comment]
Hey there!

Country should be set to “ru”. Otherwise the endpoint won’t work. Read description of PR that brings Stock endpoint in the package: https://github.com/vrslev/ikea-api-client/pull/92#issue-1130834804
This information probably should be in README 🤔

**Comment by RCRalph** [comment]
I created a pull request with the solution to this problem inside the README, feel free to merge it in, thanks for your quick response and have a nice evening!

RCRalph

**Comment by vrslev** [comment]
[Release v2.0.6](https://github.com/vrslev/ikea-api-client/releases/v2.0.6) includes the fix, you can upgrade and enjoy :)
