### ISSUE TITLE
no permission to access "http://iows.ikea.com/retail/iows/tr/tr/catalog/items/" on this server.

### ISSUE THREAD

**Issue by bgidenhsdg** [vrslev/ikea-api-client#182]
Unfortunately i do get: 
You don't have permission to access "http://iows.ikea.com/retail/iows/tr/tr/catalog/items/" on this server.

actually I do need only a code saving products in SQLITE database along with their prices, stock availabilities within specific store(s) and product urls. can you please help me how to do this?

**Comment by vrslev** [comment]
Can you share your code?

**Comment by bgidenhsdg** [comment]
well I guess it is about ikea turkey's web page. it is https://ikea.com.tr  -> also no need for country and language code. and I cannot use IOWS at all ... but let me check it once more.

**Comment by vrslev** [comment]
Closing this, if you still need help, please leave a comment.
