### ISSUE TITLE
How to get ITEMS number that has 3D model?

### ISSUE THREAD

**Issue by Nucleon729** [vrslev/ikea-api-client#233]
Hello,

I'm attempting to utilize this function:

```python
rotera_item.get_item("30221043")
```

It works perfectly until I switch to another item ID.

IE when I search for a sofa and retrieve the item number:

```python
{'itemNo': '19319220'}
```

I keep encountering the following error:

```python
ikea_api.exceptions.ItemFetchError: (404, 'Not Found')
```

HELP!

**Comment by vrslev** [comment]
Hey! Can you share a snippet of code?

Also, which country you are in?

**Comment by vrslev** [comment]
I don't think IKEA actually has 3D-model for this item. Look: https://www.ikea.com/us/en/p/finnala-sectional-4-seat-with-chaise-tallmyra-beige-s19319220/

**Comment by vrslev** [comment]
For example, this one has View in 3D button—and is available via RoterItem endpoint: https://www.ikea.com/us/en/p/klippan-loveseat-bomstad-black-50399318/
