### ISSUE TITLE
feature suggestion: Search for products by name

### ISSUE THREAD

**Issue by Erik142** [vrslev/ikea-api-client#43]
Hi again,

I believe that it would be beneficial to be able to search for products by name and get information back, including the item number for the product. I have a first implementation ready for this feature if it is of any interest to this project?

I have only tested it on the Swedish version of the corresponding IKEA API. However, the API seems to follow the same "region naming scheme" as the existing API endpoints in this project, so I believe that it should work in the same way for other regions. Let me know if this sounds interesting. If so, I'll add a PR for this 😄

**Comment by vrslev** [comment]
Hello! Sure, go ahead!
