### ISSUE TITLE
About favorites

### ISSUE THREAD

**Issue by akrisvui** [vrslev/ikea-api-client#99]
Is there any way to add "shopping list" (favorites) functionality? Does IKEA provide access to them in its api, and can you add this to your client?

**Comment by vrslev** [comment]
Привет!
There’s an API for that. It is very similar to Cart API. I didn’t implement it because don’t need it. Do you? You can contribute if you want: https://github.com/vrslev/ikea-api-client/blob/main/CONTRIBUTING.md

**Comment by akrisvui** [comment]
> There’s an API for that.
Я вижу, как вы использовали API для корзины и предметов, но не знаю откуда взять представление данных для избранного. На сайте ИКЕА API скрыто, поэтому не могли бы вы поделиться им? Вопрос глупый, но первый день занялся им и не нашел полноценного описания в интернете, только вашу адаптацию на питоне

**Comment by vrslev** [comment]
В интернете нету описания разных API, этот клиент неофициальный 😃 Я спуфил XHR-запросы и читал unminified код через Chrome DevTools.

**Comment by akrisvui** [comment]
> Я спуфил XHR-запросы и читал unminified код через Chrome DevTools.

Ох, понимаю. Сам занялся тем же самым, значит стоит продолжить. Спасибо за разъяснения.

**Comment by vrslev** [comment]
Когда разберётесь, можете поделиться информацией, может, добавим API в это проект)
